docs(maintenance): procédure d'import données en local
DNUM-SocialGouv/1j1s-etl pull request #180
Opened 2023-03-02 10:25 UTC by octohuguesdumont

UNJ1S-1385

2023-03-02 21:32 UTC, Drastal reviewed
Je te propose de supprimer quelques sauts de ligne. C'est optionnel comme genre de suggestion, le rendu du markdown sera le même.
Il y a quelques maigres corrections de français mais c'est déjà bien mieux que tout à l'heure !

2023-03-02 21:32 UTC, Drastal commented on docs/procedure/20230302-copie-donnees-prod-en-local.md
> +vous devez avoir en votre possession une clef vous permettant à vous connecter sur la production du projet.
```suggestion
Afin de pouvoir exécuter la procédure qui suit, vous devez avoir en votre possession une clef vous permettant de vous connecter sur la production du projet.
```

2023-03-02 21:32 UTC, Drastal commented on docs/procedure/20230302-copie-donnees-prod-en-local.md
> +[CLI](https://doc.scalingo.com/platform/cli/start#install-scalingo-cli)
```suggestion
Afin de manipuler les conteneurs et applications sur Scalingo, il vous faudra [installer leur CLI](https://doc.scalingo.com/platform/cli/start#install-scalingo-cli)
```
C'est plus sympa d'avoir un lien sur plus de plus de mots, ça nous évite de jouer aux fléchettes sur 5mm² 😃

2023-03-02 21:32 UTC, Drastal commented on docs/procedure/20230302-copie-donnees-prod-en-local.md
> +### Variable d'environnement utile
```suggestion
### Variables d'environnement utiles
```

2023-03-02 21:32 UTC, Drastal commented on docs/procedure/20230302-copie-donnees-prod-en-local.md
> +Dans un premier temps il vous faudra vous connecter à l'aide de votre clef
```suggestion
Dans un premier temps, il vous faudra vous connecter à l'aide de votre clef
```

2023-03-02 21:32 UTC, Drastal commented on docs/procedure/20230302-copie-donnees-prod-en-local.md
> +les commandes suivantes :
```suggestion
Pour télécharger la dernière backup de la BDD en Production, il vous faut lancer les commandes suivantes :
```

2023-03-02 21:32 UTC, Drastal commented on docs/procedure/20230302-copie-donnees-prod-en-local.md
> +il suffit de démarrer la BDD présente sur votre poste en lui chargeant le fichier.
```suggestion
Une fois le téléchargement terminé, il suffit de démarrer la BDD présente sur votre poste en lui chargeant le fichier.
```

2023-03-06 09:04 UTC, Drastal commented on docs/procedure/20230302-copie-donnees-prod-en-local.md
> +Afin de manipuler les conteneurs et applications sur Scalingo, il vous faudra [installer leur CLI](https://doc.scalingo.com/platform/cli/start#install-scalingo-cli)
Les 2 phrases commencent par _Afin de_. Tu passes la seconde avec :
> Pour manipuler...

?

2023-03-06 09:04 UTC, Drastal approved these changes

2023-03-07 08:05 UTC, Sefrancois requested changes
Je pense que ce document serait mieux dans le dépôt 1j1s-main-cms vu que c'est dans ce dépôt que se trouve la base de données.

2023-03-07 08:12 UTC, Sefrancois requested changes

2023-03-07 08:12 UTC, Sefrancois commented on docs/procedure/20230302-copie-donnees-prod-en-local.md
> +$ docker-compose cp ./tmp/backup.zip db:/backups/backup.dump
On fait le `docker compose` depuis où ? Est-ce qu'on le préciserait pas ?

2023-03-07 08:12 UTC, Sefrancois commented on docs/procedure/20230302-copie-donnees-prod-en-local.md
> +$ mkdir -p tmp
Le `mkdir -p` va créer le dossier à quel endroit ? Est-ce qu'on ne le préciserait pas ?

2023-03-07 08:17 UTC, Sefrancois commented on docs/procedure/20230302-copie-donnees-prod-en-local.md
> +$ addon_id=$(scalingo addons | grep $ADDON_NAME | cut -d'|' -f3 | tr -d ' ')
Il manque le nom de l'application ici non ?

2023-03-07 08:24 UTC, Sefrancois requested changes

2023-03-07 08:24 UTC, Sefrancois commented on docs/procedure/20230302-copie-donnees-prod-en-local.md
> +$ docker-compose exec db pg_restore -U $DATABASE_USERNAME -d $DATABASE_NAME /backups/backup.dump
Ne fonctionne pas chez moi :|

2023-03-07 08:38 UTC, octohuguesdumont commented on docs/procedure/20230302-copie-donnees-prod-en-local.md
> +$ docker-compose cp ./tmp/backup.zip db:/backups/backup.dump
j'avais essayé de rester générique

2023-03-07 08:39 UTC, octohuguesdumont commented on docs/procedure/20230302-copie-donnees-prod-en-local.md
> +$ addon_id=$(scalingo addons | grep $ADDON_NAME | cut -d'|' -f3 | tr -d ' ')
Non grâce au variable d'environnement que je fais préparé dans la session

2023-03-07 10:01 UTC, octohuguesdumont commented
Pour le choix de dépôt j'ai hésité comme on est en train d'implémenter les autres systèmes de maintenance ici

2023-03-07 10:02 UTC, octohuguesdumont commented on docs/procedure/20230302-copie-donnees-prod-en-local.md
> +$ mkdir -p tmp
alors en système unix quand on ne précise pas de chemin c'est sur place par défaut

2023-03-07 10:03 UTC, octohuguesdumont commented on docs/procedure/20230302-copie-donnees-prod-en-local.md
> +$ docker-compose exec db pg_restore -U $DATABASE_USERNAME -d $DATABASE_NAME /backups/backup.dump
On as trouvé reste a faire les MAJ de la proc ensemble.

2023-03-13 13:55 UTC, closed without merging