fix(jobteaser): filtre les stages dont la dateDebut est antérieure à …
DNUM-SocialGouv/1j1s-etl pull request #539
Opened 2024-08-09 15:20 UTC by sokl-octo

…1 mois

2024-08-12 08:17 UTC, juliebrunetto83 commented on apps/stages/src/transformation/application-service/transformer-flux-jobteaser.usecase.ts
> +		});
tu peux extraire this.dateService.maintenant()).minus({ "month": 1 }) dans une constante pour mieux lire le code

2024-08-12 08:33 UTC, juliebrunetto83 commented on apps/stages/test/transformation/application-service/transformer-flux-jobteaser.usecase.test.ts
> +					titre: "Titre de l’offre acceptée",
il y a plein d'elements que tu override qui ne sont pas utile pour le test 
Normalement la fixture devrait se suffire à elle même et tu devrai override uniquement les dates 
D'ailleurs ça serait mieux de déplacer cette partie là dans le test lui même pour que ça soit plus lisible

2024-08-12 08:36 UTC, juliebrunetto83 commented on apps/stages/test/transformation/application-service/transformer-flux-jobteaser.usecase.test.ts
> +					titre: "Titre de l’offre acceptée",
De plus, tu test les deux cas dans un seul même it ça serait bien de le séparer en deux it explicite 

"lorsque la date de début du stage est dépassé de plus d'un mois, filtre l'offre"

"lorsque la date est de début est valide, récupère l'offre"

2024-08-12 08:40 UTC, juliebrunetto83 requested changes
une petite refacto du test et c'est ok pour moi

2024-08-20 08:49 UTC, Mintoo200 approved these changes

2024-08-20 08:50 UTC, merged